version: "3"


services:
    web:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        stop_grace_period: 0s
        env_file: .env
        environment:
            PORT: 3333
            SKYLISTS_DB: ${SKYLISTS_DB}
            SKYLISTS_DB_USER: ${SKYLISTS_DB_USER}
            SKYLISTS_DB_PASSWORD: ${SKYLISTS_DB_PASSWORD}


        volumes:
            - ./data:/data
            - ../:/app
        networks:
            - network


networks:
    network:
        driver: bridge
